export const WEBDRIVER_KEYS = [
  "awesomium",
  "RunPerfTest",
  "CefSharp",
  "emit",
  "fmget_targets",
  "geb",
  "__nightmare",
  "nightmare",
  "__phantomas",
  "callPhantom",
  "_phantom",
  "spawn",
  "_Selenium_IDE_Recorder",
  "_selenium",
  "calledSelenium",
  "wdioElectron",
  "webdriver",
  "__webdriverFunc",
  "__lastWatirAlert",
  "__lastWatirConfirm",
  "__lastWatirPrompt",
  "_WEBDRIVER_ELEM_CACHE",
  "ChromeDriverw",
  "domAutomation",
  "domAutomationController",
] as const;

export const WINDOWS_FONTS = {
  "7": ["Cambria Math", "Lucida Console"],
  "8": ["Aldhabi", "Gadugi", "Myanmar Text", "Nirmala UI"],
  "8.1": ["Leelawadee UI", "Javanese Text", "Segoe UI Emoji"],
  "10": [
    "HoloLens MDL2 Assets",
    "Segoe MDL2 Assets",
    "Bahnschrift",
    "Ink Free",
  ],
  "11": ["Segoe Fluent Icons"],
} as const;
